# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: [3.8]
  # Define the workflow steps
    steps:
    # Checkout the code of the repository
        - name: Check out repository code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        # Run the mdl linting tool
        # Refers to .mdlrc file in repository
        - name: Run markdown linting
          uses: actionshub/markdownlint@master
        # Setup Python for the current language version
        - name: Setup Python ${{ matrix.python-version }}
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        # Setup Java
        - name: Set up JDK 1.8
          if: always()
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        # Check for existence of gradle files
        - name: Check for existence of git files
          uses: andstor/file-existence-action@v1
          with:
            files: "build.gradle, gradle.properties, settings.gradle, gatorgrader.yml"
        # Install pip
        - name: Install Pip
          if: always()
          run: |
            pip install -U pip
        # Install pipenv
        - name: Install Pipenv
          if: always()
          run: |
            pip install pipenv
        # Install htmlhint
        - name: Install npm
          if: always()
          run: |
            npm install
        # Java: see build.gradle
        - name: Determine gradle version
          if: always()
          run: |
            gradle --version
        # GatorGrader: see config/gatorgrader.yml
        - name: Run GatorGrader
          if: always()
          run:  |
            gradle grade
